from typing import Optional
from uuid import UUID

from od_stub_readonly import *

def create_object(object_name: Optional[str], class_name: str) -> UUID: ...
def create_link(link_name: Optional[str], assoc_name: str, src: UUID, tgt: UUID) -> UUID: ...
def delete(obj: UUID) -> None: ...
def set_slot_value(obj: UUID, attr_name: str, new_value: any, is_code=False) -> None: ...